language: php
php:
  - 7.2
  - 7.3
  - 7.4

os: linux

dist: bionic

services:
  - couchdb

before_script:
  - sudo apt-get install libcurl4-openssl-dev
  - curl -X PUT localhost:5984/testdb

script:
  - phpize
  - ./configure --enable-couchdb_ext
  - make && make test
