name: ext-couchdb CI
on: [push, pull_request]
jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1']
        couchdb: ['3', '2.3']
    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
      - name: Install CouchDB
        uses: iamssen/couchdb-github-action@master
        with:
          couchdb-version: ${{ matrix.couchdb }}
      - name: Install libcurl
        run: |
          sudo apt-get install libcurl4-openssl-dev
      - name: Authenticate CouchDB admin user
        run: |
          curl -X POST -H 'content-type: application/json' -d '{"name": "admin", "password": "password"}' http://localhost:5984/_session
      - name: Install async.h
        run: |
          sudo sh async.sh
      - name: Run tests
        run: |
          phpize && ./configure --enable-couchdb && \
          make && make test
